# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c8a2c368d7bcbbe7bfc5b0b4cc6423834510f752afa5c65181856403314ba3d83f25228b43830ea54bbcb8ab5df6d693968da80f2f9ef9c0087e8f8173717a

test:
  secret_key_base: ac65fac4ded59804dadcae5edad9343f53c89456c49977192e5f71b2b490324d91840af4ec571a73453c1e344f8f7c67bb6c1dbd2fdccad5462bf594756e4309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
